### PR TITLE
Suggestions

### PR DESCRIPTION
**Pull request by mohammed-ali-1**
Some suggestions on improving the README

### CODE REVIEW

**Comment by bloeys** [comment]
To add to this, I would move the DPAutoFlow to the top of the docs not the bottom.
Step by step, fully automated quick start should be the first thing then the details.

**Comment by mohammed-ali-1** [comment]
@MEnnabah if you have already integrated this, please close this issue.

**Comment by bloeys** [comment]
@mohammed-ali-1 Please resolve the conflicts as they come from your PR changes ;)

**Comment by mohammed-ali-1** [comment]
@bloeys I resolved the conflicts. But I remember Ennabah saying he wants to edit manually and push separately.

**Comment by mohammed-ali-1** [comment]
I'm closing this issue.

**Pull request closed without merging**
